name: habit_builder
description: A habit-building fitness app for tracking wellness goals

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # HTTP & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3

  # Navigation - ADD THIS
  go_router: ^12.1.1

  # UI & Charts
  fl_chart: ^0.64.0
  table_calendar: ^3.0.9
  lottie: ^2.7.0
  cached_network_image: ^3.3.0

  # Utilities
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1
  permission_handler: ^11.0.1
  intl: ^0.18.1  # ADD THIS



  # Notifications
  #flutter_local_notifications: ^16.1.0

  # JWT & Auth
  jwt_decoder: ^2.0.1

  # Functional Programming - ADD THIS
  dartz: ^0.10.1

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.7

  path_provider: ^2.1.1
  hive_generator: ^2.0.1

  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4

  # Testing
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
